name: C# Build

on:
  push:
    branches:
      - main  # Runs on every push to the main branch
  pull_request:
    branches:
      - main  # Runs on every pull request to main

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Clones the repository

      - name: Set Up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Installs .NET 7.x

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore Dependencies
        run: dotnet restore  # Ensures dependencies are installed

      - name: Build the Project
        run: dotnet build --no-restore --configuration Release  # Builds the project
